run:
    concurrency: 4
    deadline: 3m
    issues-exit-code: 1
    tests: false
    skip-files:
        - ".*_mock\\.go"
        - "mock_.*\\.go"

output:
    format: colored-line-number
    print-issued-lines: true
    print-linter-name: true
